module.exports = Object.freeze({
  CLIENT_CREATE: 'CLIENT-CREATE',
  CLIENT_READ: 'CLIENT-READ',
  CLIENT_UPDATE: 'CLIENT-UPDATE',
  CLIENT_DELETE: 'CLIENT-DELETE',
  SERVER_CREATE: 'SERVER-CREATE',
  SERVER_READ: 'SERVER-READ',
  SERVER_UPDATE: 'SERVER-UPDATE',
  SERVER_DELETE: 'SERVER-DELETE',

  /* General Errors */
  INVALID_ID: 'INVALID_ID',
  INVALID_VALUE: 'INVALID-VALUE',
  INVALID_FIELD: 'INVALID-FIELD',
  NOT_FOUND: 'NOT_FOUND',
  MISSING_PARAMS_OR_DATA: 'MISSING-PARAMS-OR-DATA',
  DUPLICATE_KEY: 'DUPLICATE-KEY',
  USER_ID_NOT_FOUND: 'USER_ID_NOT_FOUND',

  /* Country Related Errors */
  INVALID_COUNTRY: 'INVALID-COUNTRY',

  /* Account & Auth Related Errors */
  INVALID_TOKEN: 'INVALID-TOKEN',
  TOKEN_EXPIRED: 'TOKEN-EXPIRED',
  TOO_MANY_REQUESTS: 'TOO-MANY-REQUESTS',
  PASSWORD_RESET_FAIL: 'PW-RESET-FAIL',
  RESEND_ACTIVATION_FAIL: 'RSND-ACTI-FAIL',
  USER_ALREADY_EXIST: 'USER-ALREADY-EXIST',
  NON_EXIST_ACCOUNT: 'NO-ACCOUNT',
  WRONG_PASSWORD: 'WRONG-PASSWORD',
  WRONG_OLD_PASSWORD: 'WRONG-OLD-PASSWORD',
  UNAUTHORIZED_OPERATION: 'UNAUTHORIZED-OPERATION',
  INVALID_PERMISSION: 'INVALID-PERMISSION',
  EMAIL_PW_NT_MATCH: 'EMAIL-PW-NOT-MATCH',

  /* User Creation */
  EMAIL_MISSING: 'EMAIL-MISSING',
  INVALID_EMAIL: 'INVALID-EMAIL',
  EMAIL_ALREADY_EXIST: 'EMAIL-ALREADY-EXIST',

  /* Email Related Errors */
  EMAIL_SEND_FAILED: 'EMAIL-SEND-FAILED',
  EMAIL_NOTIFICATION_EXIST: 'EMAIL-NOTIFICATION-EXIST',

  /* gender related Errors */
  INVALID_GENDER: 'INVALID-GENDER',
});
